//Podemos mudar LOOKAHEAD dinamicamente (p.exemplo para int vs int[])
options 
{
    LOOKAHEAD = 1;
}

PARSER_BEGIN(JavaMM)

    import java.io.FileInputStream;

    public class JavaMM
    {
        public static void main(String[] args) throws Exception
        {
            if(args.length < 1)
            {
                System.out.println("Usage: JavaMM <filename>");
                System.exit(1);
            }

            JavaMM parser = new JavaMM(new FileInputStream(args[0]));
            SimpleNode root = parser.Program();

            System.out.println("-----AST-----");
            root.dump(" ");
            
        }
    }

PARSER_END(JavaMM)

SKIP :
{
    " " 
    | "\r" 
    | "\t"
    | "\n"
    | <"//" (~["\n","\r"])* ("\n" | "\r" | "\r\n")>
    | <"/*" (~["*"])* "*" ("*" | ~["*","/"] (~["*"])* "*")* "/">
}

TOKEN:
{
    
    <BOOL: "boolean">
    | <MAIN: "main">
    | <VOID: "void">
    | <STRING: "String">
    | <INT: ("int")>
    | <LPAREN: "(">
    | <RPAREN: ")">
    | <LBRACK: "[">
    | <RBRACK: "]">
    | <LBRACE: "{">
    | <RBRACE: "}">
    | <ADD: "+">
    | <SUB: "-">
    | <MUL: "*">
    | <DIV: "/">
    | <NOT: "!">
    | <EQUAL: "=">
    | <LOWER: "<">
    | <BIGGER: ">">
    | <AND: "&&">
    | <SEMI: ";">
    | <COMMA: ",">
    | <DOT: ".">
    | <RETURN: "return">
    | <PUBLIC: "public">
    | <STAT: "static">
    | <TRUE: "true">
    | <FALSE: "false">
    | <THIS: "this">
    | <NEW: "new">
    | <IF: "if">
    | <ELSE: "else">
    | <WHILE: "while">
    | <CLASS: "class">
    | <EXT: "extends">
    | <INTEGER: (<DIGIT>)+>
    | <IDENTIFIER: <LETTER> (<LETTER> | <DIGIT>)*>
    | <LETTER: ["$", "a"-"z", "A"-"Z", "_"]>
    | <DIGIT: ["0"-"9"]>
}

SimpleNode Program(): {} 
{
    ClassDeclaration() <EOF> {return jjtThis;}
}

void ClassDeclaration() #class_declaration: {}
{
    <CLASS> <IDENTIFIER> [<EXT> <IDENTIFIER>] 
    <LBRACE> (VarDeclaration())* (<PUBLIC> (MainDeclaration() | MethodDeclaration()))* <RBRACE>
}

void VarDeclaration() #var: {}
{
    Type() <IDENTIFIER> <SEMI>  
}

void MainDeclaration() #main: {}
{
    <STAT> <VOID> <MAIN> <LPAREN> <STRING> <LBRACK> <RBRACK> <IDENTIFIER> <RPAREN> 
    <LBRACE>  (LOOKAHEAD(2) VarDeclaration())* (Statement())* <RBRACE>  
}

// Como certificar que o tipo do return é o mesmo que o "return em si"? Prolly so em analise semantica
void MethodDeclaration(): {}
{
    Type() Method() <RETURN> Expression() <SEMI> <RBRACE>
}

void Method(): {}
{
    <IDENTIFIER> <LPAREN> [Type() <IDENTIFIER> (<COMMA> Type() <IDENTIFIER>)*] <RPAREN>
    <LBRACE> (LOOKAHEAD(2) VarDeclaration())* (Statement())*
}

void Type(): {}
{
    <INT> [<LBRACK> <RBRACK>]
    | <BOOL>
    | <IDENTIFIER>
}

void Statement() #void: {}
{
    <LBRACE> (Statement())* <RBRACE>
    | While()
    | If()
    | Expression() <SEMI>
    | <IDENTIFIER> (<EQUAL> Expression() <SEMI> | <LBRACK> Expression() <RBRACK> <EQUAL> Expression() <SEMI>)   
}

void While(): {}
{
    <WHILE> <LPAREN> BOOLEAN_EXPR() <RPAREN> Statement()
}

void If(): {}
{
    <IF> <LPAREN> BOOLEAN_EXPR() <RPAREN> Statement() [Else()]
}

void Else(): {}
{
    <ELSE> Statement()
}

// Ver como distinguir boolean expressions de arithmetic
void Expression(): {}
{
    <TRUE>
    | <INTEGER>
    /*
    Expression() (<AND> | <LOWER> | <BIGGER> | <ADD> | <SUB> | <MUL> | <DIV>)* Expression()   
    | Expression() <LBRACK> <RBRACK> Expression()
    | Expression() <DOT> "length"
    | Expression() <DOT> <IDENTIFIER> <LPAREN> [Expression() (<COMMA> Expression())*] <RPAREN>
    | <TRUE>
    | <FALSE>
    | <IDENTIFIER>
    | <THIS>
    | <INTEGER>
    | <NEW> <INT> <LBRACK> Expression() <RBRACK>
    | <NEW> <IDENTIFIER> <LPAREN> <RPAREN> //E classes com argumentos no construtor?
    | <NOT> Expression()
    | <LPAREN> Expression() <RPAREN> */
}

void BOOLEAN_EXPR(): {}
{
    BOOL_EXPR() [<AND> BOOLEAN_EXPR()]
    | <TRUE>
    | <FALSE>
}

void BOOL_EXPR(): {}
{
    ARIT_EXPR() <LOWER> ARIT_EXPR()
}

void ARIT_EXPR(): {}
{
    ARIT_EXPR_2(1)
    [
        (<ADD> ARIT_EXPR_2(1) | <SUB> ARIT_EXPR_2(1))
    ]
}

void ARIT_EXPR_2(int sign): {}
{
    ARIT_EXPR_3(sign)
    [
        (<MUL> ARIT_EXPR_3(sign) | <DIV> ARIT_EXPR_3(sign))
    ]
}

void ARIT_EXPR_3(int sign): {}
{
    <INTEGER>
    | <SUB> ARIT_EXPR_3(-1)
    | <LPAREN> ARIT_EXPR() <RPAREN>
    | <IDENTIFIER>
}