/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 6.0_1 */

package ast;

public interface JavaMMTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTEXTENDS = 2;
  public int JJTVAR = 3;
  public int JJTMAIN = 4;
  public int JJTMETHOD = 5;
  public int JJTRETURN = 6;
  public int JJTARG = 7;
  public int JJTVOID = 8;
  public int JJTEQUALS = 9;
  public int JJTTERM = 10;
  public int JJTWHILE = 11;
  public int JJTIF = 12;
  public int JJTELSE = 13;
  public int JJTMEMBER = 14;
  public int JJTARRAYACCS = 15;
  public int JJTAND = 16;
  public int JJTLOWER = 17;
  public int JJTADD = 18;
  public int JJTSUB = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTNOT = 22;
  public int JJTENCLOSED_EXPR = 23;


  public String[] jjtNodeName = {
    "Program",
    "Class",
    "Extends",
    "Var",
    "Main",
    "Method",
    "Return",
    "Arg",
    "void",
    "EQUALS",
    "TERM",
    "While",
    "If",
    "Else",
    "Member",
    "ArrayAccs",
    "AND",
    "LOWER",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "NOT",
    "ENCLOSED_EXPR",
  };
}
/* JavaCC - OriginalChecksum=640f411346f78310114ecb5d6fdf45e8 (do not edit this line) */
