/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 6.0_1 */
public interface JavaMMTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTVAR = 2;
  public int JJTMAIN = 3;
  public int JJTMETHOD = 4;
  public int JJTRETURN = 5;
  public int JJTARG = 6;
  public int JJTVOID = 7;
  public int JJTEQUALS = 8;
  public int JJTSTMT = 9;
  public int JJTLHS = 10;
  public int JJTWHILE = 11;
  public int JJTIF = 12;
  public int JJTELSE = 13;
  public int JJTMEMBER = 14;
  public int JJTEXPRESSION = 15;
  public int JJTAND = 16;
  public int JJTLOWER = 17;
  public int JJTADD = 18;
  public int JJTSUB = 19;
  public int JJTMUL = 20;
  public int JJTDIV = 21;
  public int JJTNOT = 22;
  public int JJTTERM = 23;
  public int JJTENCLOSED_EXPR = 24;


  public String[] jjtNodeName = {
    "Program",
    "Class",
    "Var",
    "Main",
    "Method",
    "Return",
    "Arg",
    "void",
    "EQUALS",
    "Stmt",
    "lhs",
    "While",
    "If",
    "Else",
    "Member",
    "Expression",
    "AND",
    "LOWER",
    "ADD",
    "SUB",
    "MUL",
    "DIV",
    "NOT",
    "TERM",
    "ENCLOSED_EXPR",
  };
}
/* JavaCC - OriginalChecksum=80162819ac44eb400659a98c5c26ac78 (do not edit this line) */
