/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 6.0_1 */
public interface JavaMMTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTVAR = 2;
  public int JJTMAIN = 3;
  public int JJTMETHOD = 4;
  public int JJTRETURN = 5;
  public int JJTARG = 6;
  public int JJTVOID = 7;
  public int JJTSTMT = 8;
  public int JJTWHILE = 9;
  public int JJTIF = 10;
  public int JJTELSE = 11;
  public int JJTMEMBER = 12;
  public int JJTEXPRESSION = 13;
  public int JJTEXPR = 14;
  public int JJTEXPR_2 = 15;
  public int JJTEXPR_3 = 16;


  public String[] jjtNodeName = {
    "Program",
    "Class",
    "Var",
    "Main",
    "Method",
    "Return",
    "Arg",
    "void",
    "Stmt",
    "While",
    "If",
    "Else",
    "Member",
    "Expression",
    "EXPR",
    "EXPR_2",
    "EXPR_3",
  };
}
/* JavaCC - OriginalChecksum=f997b3b6a8d7dc639a83f7e3187aeba8 (do not edit this line) */
