/* Generated By:JavaCC: Do not edit this line. JavaMMTreeConstants.java Version 6.0_1 */
public interface JavaMMTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASS = 1;
  public int JJTVAR = 2;
  public int JJTMAIN = 3;
  public int JJTVOID = 4;
  public int JJTMETHOD = 5;
  public int JJTARG = 6;
  public int JJTSTMT = 7;
  public int JJTWHILE = 8;
  public int JJTIF = 9;
  public int JJTELSE = 10;
  public int JJTMEMBER = 11;
  public int JJTEXPRESSION = 12;
  public int JJTEXPR = 13;
  public int JJTEXPR_2 = 14;
  public int JJTEXPR_3 = 15;


  public String[] jjtNodeName = {
    "Program",
    "Class",
    "Var",
    "Main",
    "void",
    "Method",
    "Arg",
    "Stmt",
    "While",
    "If",
    "Else",
    "Member",
    "Expression",
    "EXPR",
    "EXPR_2",
    "EXPR_3",
  };
}
/* JavaCC - OriginalChecksum=47448eb789d2222bc6b1ae29cc7f5c85 (do not edit this line) */
